server {
    
    # SSL/TLS configuration
    listen 443 ssl;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # server_name / root directory / index files
    server_name doberes.42.fr;
    root /var/www/html;
    index index.html index.htm index.php;

    # Static file handling
    # for every request, try to serve the file directly, if not found, return a 404 error
    location / {
        try_files $uri $uri/ =404;
    }

    # PHP processing
    # for requests ending with .php, pass the request to the FastCGI server (WordPress container) for processing
    # location ~ \.php$ {
    #     include snippets/fastcgi-php.conf;
    #     fastcgi_pass wordpress:9000;
    # }
}