services:

#? ---------------------------------------------------------
#? MARIADB
#? ---------------------------------------------------------

  mariadb:
    container_name: inception_mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_password
      - db_root_password

#? ---------------------------------------------------------
#? WORDPRESS - depends on mariadb
#? ---------------------------------------------------------

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #   image: wordpress
  #   container_name: wordpress
  #   restart: unless-stopped
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - inception
  #   env_file:
  #     - .env
  #   secrets:
  #     - db_password

#? ---------------------------------------------------------
#? NGINX - depends on wordpress
#? ---------------------------------------------------------
  nginx:
    container_name: inception_nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    env_file:
      - .env
    # depends_on:
    #  - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped

# ---------------------------------------------------------
# NETWORKS
# ---------------------------------------------------------

networks:
  inception_network:
    driver: bridge

# ---------------------------------------------------------
# VOLUMES
# ---------------------------------------------------------

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/doberes/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/doberes/data/mariadb

# ---------------------------------------------------------
# SECRETS
# ---------------------------------------------------------

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt