# Penultimate stable version of Debian, as required by the subject.
# Debian 13 "Trixie" is the current stable release (since Aug 2025).
# Debian 12 "Bookworm" is therefore the penultimate stable version
# (oldstable since July 2026, now in LTS support until June 2028).
FROM debian:12.15-slim